# Generated by Django 2.1.5 on 2019-07-24 17:38

from django.db import migrations, models
import django.db.models.deletion
import easyvolunteer.models


class Migration(migrations.Migration):

    dependencies = [
        ('easyvolunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', easyvolunteer.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='easyvolunteer.Brand'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organ',
            field=models.BooleanField(default=False, verbose_name='기관 여부'),
        ),
    ]
